# coding: utf-8

"""
    Accounting service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_accounting.models.accounts_receivable_transaction_response_transfer_details import AccountsReceivableTransactionResponseTransferDetails

class TestAccountsReceivableTransactionResponseTransferDetails(unittest.TestCase):
    """AccountsReceivableTransactionResponseTransferDetails unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountsReceivableTransactionResponseTransferDetails:
        """Test AccountsReceivableTransactionResponseTransferDetails
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountsReceivableTransactionResponseTransferDetails`
        """
        model = AccountsReceivableTransactionResponseTransferDetails()
        if include_optional:
            return AccountsReceivableTransactionResponseTransferDetails(
                reservation = cloudbeds_accounting.models.reservation_transfer_details.ReservationTransferDetails(
                    id = '', 
                    identifier = '', 
                    guest_name = '', 
                    status = 'checked_out', 
                    checkin_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                    checkout_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ),
                group_profile = cloudbeds_accounting.models.group_profile_transfer_details.GroupProfileTransferDetails(
                    id = '', 
                    name = '', 
                    code = '', )
            )
        else:
            return AccountsReceivableTransactionResponseTransferDetails(
        )
        """

    def testAccountsReceivableTransactionResponseTransferDetails(self):
        """Test AccountsReceivableTransactionResponseTransferDetails"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
