# coding: utf-8

"""
    Accounting service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_accounting.models.post_group_profile_balance_transfer_request import PostGroupProfileBalanceTransferRequest

class TestPostGroupProfileBalanceTransferRequest(unittest.TestCase):
    """PostGroupProfileBalanceTransferRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> PostGroupProfileBalanceTransferRequest:
        """Test PostGroupProfileBalanceTransferRequest
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `PostGroupProfileBalanceTransferRequest`
        """
        model = PostGroupProfileBalanceTransferRequest()
        if include_optional:
            return PostGroupProfileBalanceTransferRequest(
                folio_id = 56
            )
        else:
            return PostGroupProfileBalanceTransferRequest(
        )
        """

    def testPostGroupProfileBalanceTransferRequest(self):
        """Test PostGroupProfileBalanceTransferRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
