# coding: utf-8

"""
    Accounting service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_accounting.models.transaction_item_group import TransactionItemGroup

class TestTransactionItemGroup(unittest.TestCase):
    """TransactionItemGroup unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTransactionItemGroup(self):
        """Test TransactionItemGroup"""
        # inst = TransactionItemGroup()

if __name__ == '__main__':
    unittest.main()
