# coding: utf-8

"""
    Accounting service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from cloudbeds_accounting.models.accounts_receivable_transaction_paginated import AccountsReceivableTransactionPaginated

class TestAccountsReceivableTransactionPaginated(unittest.TestCase):
    """AccountsReceivableTransactionPaginated unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AccountsReceivableTransactionPaginated:
        """Test AccountsReceivableTransactionPaginated
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AccountsReceivableTransactionPaginated`
        """
        model = AccountsReceivableTransactionPaginated()
        if include_optional:
            return AccountsReceivableTransactionPaginated(
                content = [
                    cloudbeds_accounting.models.accounts_receivable_transaction_response.AccountsReceivableTransactionResponse(
                        id = '', 
                        transaction_date = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        amount = 1.337, 
                        internal_transaction_code = '', 
                        description = '', 
                        notes = '', 
                        currency = '', 
                        currency_scale = 56, 
                        posted = True, 
                        user = cloudbeds_accounting.models.user_model.UserModel(
                            id = '', 
                            first_name = '', 
                            last_name = '', 
                            email = '', 
                            type = 'REAL_USER', ), 
                        actions = [
                            cloudbeds_accounting.models.action.Action(
                                type = '', 
                                parameters = {
                                    'key' : ''
                                    }, )
                            ], 
                        transfer_details = cloudbeds_accounting.models.accounts_receivable_transaction_response_transfer_details.AccountsReceivableTransactionResponse_transferDetails(
                            reservation = cloudbeds_accounting.models.reservation_transfer_details.ReservationTransferDetails(
                                id = '', 
                                identifier = '', 
                                guest_name = '', 
                                status = 'checked_out', 
                                checkin_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), 
                                checkout_date = datetime.datetime.strptime('1975-12-30', '%Y-%m-%d').date(), ), 
                            group_profile = cloudbeds_accounting.models.group_profile_transfer_details.GroupProfileTransferDetails(
                                id = '', 
                                name = '', 
                                code = '', ), ), )
                    ],
                next_page_token = ''
            )
        else:
            return AccountsReceivableTransactionPaginated(
        )
        """

    def testAccountsReceivableTransactionPaginated(self):
        """Test AccountsReceivableTransactionPaginated"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
