# coding: utf-8

"""
    Accounting service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from cloudbeds_accounting.models.transaction_item_group import TransactionItemGroup
from typing import Optional, Set
from typing_extensions import Self

class CustomTransactionCodesModel(BaseModel):
    """
    CustomTransactionCodesModel
    """ # noqa: E501
    id: Optional[StrictStr] = None
    version: Optional[StrictInt] = None
    name: Annotated[str, Field(min_length=1, strict=True)]
    code: Annotated[str, Field(min_length=1, strict=True)] = Field(description="The custom code assigned by the user.")
    transaction_item_code: Optional[StrictStr] = Field(default=None, description="The system code that cannot be modified.", alias="transactionItemCode")
    sku: Optional[Annotated[str, Field(min_length=1, strict=True)]] = None
    item_group: Optional[TransactionItemGroup] = Field(default=None, alias="itemGroup")
    custom_general_ledger_code_id: Optional[StrictStr] = Field(default=None, alias="customGeneralLedgerCodeId")
    item_id: Optional[StrictStr] = Field(default=None, description="Item ID for items_services group", alias="itemId")
    pos_item_id: Optional[StrictStr] = Field(default=None, description="POS Item ID for items_services group", alias="posItemId")
    tax_id: Optional[StrictStr] = Field(default=None, description="Tax ID for taxes_fees group (taxes)", alias="taxId")
    fee_id: Optional[StrictStr] = Field(default=None, description="Fee ID for taxes_fees group (fees)", alias="feeId")
    payment_id: Optional[StrictStr] = Field(default=None, description="Payment ID for payments group", alias="paymentId")
    space_id: Optional[StrictStr] = Field(default=None, description="Space ID for spaces group", alias="spaceId")
    __properties: ClassVar[List[str]] = ["id", "version", "name", "code", "transactionItemCode", "sku", "itemGroup", "customGeneralLedgerCodeId", "itemId", "posItemId", "taxId", "feeId", "paymentId", "spaceId"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of CustomTransactionCodesModel from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of CustomTransactionCodesModel from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "id": obj.get("id"),
            "version": obj.get("version"),
            "name": obj.get("name"),
            "code": obj.get("code"),
            "transactionItemCode": obj.get("transactionItemCode"),
            "sku": obj.get("sku"),
            "itemGroup": obj.get("itemGroup"),
            "customGeneralLedgerCodeId": obj.get("customGeneralLedgerCodeId"),
            "itemId": obj.get("itemId"),
            "posItemId": obj.get("posItemId"),
            "taxId": obj.get("taxId"),
            "feeId": obj.get("feeId"),
            "paymentId": obj.get("paymentId"),
            "spaceId": obj.get("spaceId")
        })
        return _obj


