# coding: utf-8

"""
    Accounting service API

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

    The version of the OpenAPI document: v0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class TransactionItemGroup(str, Enum):
    """
    TransactionItemGroup
    """

    """
    allowed enum values
    """
    ITEMS_SERVICES = 'items_services'
    RESERVATIONS = 'reservations'
    TAXES_FEES = 'taxes_fees'
    PAYMENTS = 'payments'
    ACCRUAL_ACCOUNTING = 'accrual_accounting'
    CUSTOM_ITEM = 'custom_item'
    SPACES = 'spaces'
    ACCOUNTS_RECEIVABLE_TRANSFERS = 'accounts_receivable_transfers'
    DEPOSIT_TRANSFERS = 'deposit_transfers'
    UNKNOWN_DEFAULT_OPEN_API = 'unknown_default_open_api'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of TransactionItemGroup from a JSON string"""
        return cls(json.loads(json_str))

    @classmethod
    def _missing_(cls, value):
        """Handle unknown enum values by returning the unknown default case."""
        return cls.UNKNOWN_DEFAULT_OPEN_API

